package.json, src/verifier.js, src/verifier.spec.js
[It works](https://ci.appveyor.com/project/MichelBoudreau/pact-node/build/28)!
* A number of changes to the upstream projects (pact-provider-verifier and the npm module) to fix Windows encoding issues
* Sanitise URLs on Windows paths to work in Ruby land
=> Provider verification and Pact Publishing...on Windows!

src/verifier.js, test/verifier.integration.spec.js
Fixes issue #7.
Essentially, we log all output as before, but we also store it in a string variable that is passed back to the promise chain. This allows clients (such as pact-foundation/pact-js) to provide better messaging to their users.
See https://github.com/pact-foundation/pact-node/pull/8/ (using branches in this repo so I can kill my old one).
=> Return output to promise in verification process #8

src/publisher.js, test/integration/brokerMock.js, test/publisher.integration.spec.js
Addresses comment: https://github.com/pact-foundation/pact-node/commit/a5afdb17e2c3ca8acf6c6a2051e7575cc4bcb4b2?diff=unified#commitcomment-17854867
New checks:
* Existence of remote files (will use basic auth if provided)
* Sanity check that a consumer/provider has been added to the Pact file
=> Validate remote Pact files on publish

README.md, src/publisher.js, src/publisher.spec.js, test/integration/brokerMock.js, test/publisher.integration.spec.js
the pact broker allows for an endpoint that takes only one tag as specified here: https://github.com/bethesque/pact_broker/wiki/How-to-ensure-backwards-compatibility-by-tagging-pacts
This change creates an array of promises to loop through the array of tags and sends a PUT request to the Pact Broker accordingly, returning the original `deferred` object when all is done.
Feedback welcome.
=> adding tagging capability

src/publisher.js, src/publisher.spec.js, test/integration/brokerMock.js
A couple of things:
First, the URL was wrong, oversight on my part as it should have been `../versions/..` instead of `../version/..`
Then the `json: true` configuration on the module `request` updates the headers with Accept and Content-Type pointing to JSON. Unfortunately the Pact Broker was rejecting this with a HTTP 406...
> 406 Not acceptable
> The resource is valid, but cannot be provided in a format specified in the Accept headers in the request.
Fixed that too.
=> fix(tag): fix URL for Pact tagging

src/verifier.js, src/verifier.spec.js
Wraps all arguments to the verifier in quotation marks, to allow for arguments with special characters (see #22 for example with passwords).
=> fix(cmd): quote command line invocation arguments, fixes #22

README.md, src/verifier.js, src/verifier.spec.js
Fixes #30, but please count this as a proposal rather than a full-blown PR. I haven't fully explored test coverage etc. at this point.
Adds ability for a user to specify a timeout on the verification process. Previously there was a 10s verification timeout.
Another alternative could be to remove the timeout altogether and simply allow the parent testing framework to perform the timeout.
Looking for your thoughts @mboudreau.
=> PROPOSAL: Allow user to specify verification timeout

README.md, package.json, src/verifier.js, src/verifier.spec.js, test/integration/provider.js, test/integration/publish-verification-example-fail.json, test/integration/publish-verification-example-success.json, test/verifier.integration.spec.js
Adds support for a new feature of the broker - the ability to send provider verification results back to the Broker, allowing more intelligent CI practices.
The main use case this solves is allowing you (probably via a CI / CD processe) to detect Consumer changes that have not yet been verified by a provider. Publishing the status to the broker allows tooling to then query this status, and block a deployment if the contract has changed or has not been verified since last published.
See https://github.com/realestate-com-au/pact/blob/master/CHANGELOG.md#1110-8-may-2017 for more.
**Commit details**:
- Add flags to automatically publish verification results to
Pact broker
- Had to hard code port in integration test as verifier reads
broker URL dynamically from pact (see …
=> feat(verifications): publish verifications to broker

README.md, package.json, src/broker.js, src/broker.spec.js, src/verifier.js, src/verifier.spec.js, test/integration/brokerMock.js
This feature allows a user to simply point at a Pact Broker via `pactBrokerUrl` with a Provider name (`provider`), optionally passing in a set of `tags`, and the library will automatically pull in all pacts for the given Provider.
This is the ideal way of finding pacts, rather than hard coding locations per consumer/version/tag etc.
The integration tests aren't fully featured, but they do show the underlying Ruby process is actually being properly executed which was my intention. The unit tests should do the job in terms of functionality.
=> Fetch from broker: Allow verifier to fetch pacts from a Broker

README.md, package.json, src/verifier.js, test/mocha.opts, test/verifier.integration.spec.js
Since the verifier `v1.1.3` the states URL is no longer required and is ignored - huzzah!
This PR removes the need for it and adds a deprecation warning.
Also, there was some minor formatting (spaces where there needed be any) in the verifier that my editor has kindly removed.
=> Deprecate providerStatesUrl

README.md
Fixes https://github.com/pact-foundation/pact-js/issues/86
=> docs(mockserver): updating support for 0.0.0.0 as host option

.editorconfig, bin/pact-cli.spec.ts, bin/pact-cli.ts, package.json, src/broker.ts, src/logger.ts, src/pact-util.ts, src/pact.spec.ts, src/pact.ts, src/publisher.spec.ts, src/publisher.ts, src/server.spec.ts, src/server.ts, src/verifier.spec.ts, src/verifier.ts, test/integration/broker-mock.ts, test/integration/data-utils.ts, test/integration/provider-mock.ts, test/mocha.opts, tsconfig.json
Adds the following TS configuration, in order to improve the libraries portability into other TS projects:
* --noImplicitAny: Raise error on expressions and declarations with an implied any type.
* --noImplicitReturns: Report error when not all code paths in function return a value.
* --noImplicitThis: Raise error on this expressions with an implied any type.
* --strictNullChecks: In strict null checking mode, the nulland undefined values are not in the domain of every type and are only assignable to themselves and any (the one exception being that undefined is also assignable to void).
NOTE: in a few q-related cases, explicit type casting was necessary. I haven't been able to dig far enough into why the code works but types are incorrect - either there is an issue with the code, or the …
=> Improve type checking across codebase

.npmignore
This is part of fixing #69.
Per https://github.com/Microsoft/TypeScript/issues/7432 the TypeScript compiler will attempt to
compile the TypeScript sources if they're found. This is because definitions (.d.ts) do not take
precedence over source files.
New package contents:
```
$ npm pack
$ tar -tf pact-foundation-pact-node-6.7.2.tgz --wildcards 'package/src/*.ts'
package/src/publisher.d.ts
package/src/index.d.ts
package/src/pact.d.ts
package/src/pact.spec.d.ts
package/src/index.spec.d.ts
package/src/broker.spec.d.ts
package/src/publisher.spec.d.ts
package/src/server.d.ts
package/src/logger.d.ts
package/src/server.spec.d.ts
package/src/broker.d.ts
package/src/service.d.ts
package/src/stub.d.ts
package/src/pact-util.d.ts
package/src/stub.spec.d.ts
package/src/verifier.d.ts …
```
=> Avoids packaging TypeScript sources to avoid .d.ts conflicts

.travis.yml, bin/pact-cli.spec.ts, package.json, src/pact-util.ts, src/stub.spec.ts, standalone/install.ts, test/integration/me-they-weird path-success.json, test/integration/publish-verification-example weird path-success.json, test/verifier.integration.spec.ts
Had to fix pact-support and the .bat wrappers in pact-ruby-standalone so that it can support spaces in paths when on windows.
=> fix(windows-path): spaces in paths on windows would error our the pact binary

README.md, bin/pact-cli.spec.ts, package.json, src/pact-standalone.spec.ts, src/pact-standalone.ts, src/pact-util.ts, src/pact.ts, src/service.ts, standalone/install.ts
Showing a warning with a way to fix the situation if not.  The check involves creating a directory path that's longer than 260 characters to see if that crashes, if it does, show a warning to the user, if not, Windows is good to go.
=> fix(windows-long-path): Checking if Windows has long path enabled

bin/pact-cli.spec.ts
While working on `can-i-deploy`, I noticed that the test for `publish` called `verify` instead in one of the test cases. This commit corrects the test.
=> test(pact-cli): correct publish test to ensure it calls the right code

package.json
The readme says that `npm run watch` is the right way to start autorefreshing lint and test for development, but the script doesn't exist at the moment.
The `watch` script was removed a year ago in f304c5c261cfef58042cbf38ef25c4fb0a76c59f - but I can't see why, and it seems to still work. 
This PR puts it back, but if it were intentionally removed, we should reject this PR and instead update the documentation. I'm putting this PR up for review, because I'm not familiar with the history here.
=> chore(scripts): put watch script back

package.json
Currently a repository including `pact-node` gets the following warnings in the GitHub gui:
For `request@2.83.0`,  the problem library `cryptiles` was brought in by `hawk`:
```
$ npm ls cryptiles
@pact-foundation/pact-node@6.19.11 /Users/work/office/pact/pact-node
└─┬ request@2.83.0
└─┬ hawk@6.0.2
└── cryptiles@3.1.2
```
This PR upgrades `request`. Since later versions of request no longer depend on `hawk` or `cryptiles`, this will remove the warning in future releases.
```
$ npm ls cryptiles
@pact-foundation/pact-node@6.19.11 /Users/work/office/pact/pact-node
└── (empty)
```
*Aside:* The latest version of `request` is actually `2.88.0` (as suggested by [this dependabot PR](https://github.com/pact-foundation/pact-node/pull/130)). However, the [travis build for …
=> build(deps): Fix GitHub warning by updating request from 2.83.0 to 2.87.0

bin/pact-cli.spec.ts, bin/pact-cli.ts, package.json, src/can-deploy.spec.ts, src/can-deploy.ts, src/pact-util.spec.ts, src/pact-util.ts, src/pact.ts, standalone/install.ts
This PR adds the `can-i-deploy` to the API and CLI tools.
Since it's my first substantial change to pact-node, I'd like to highlight some discussion points:
* Because the order of arguments to `can-i-deploy` matters, but the previous way of handing options off to `PactUtil` doesn't let you specify order of arguments (or even the same argument more than once), I've added a helper in `CanDeploy` to take the options object and convert it into an array of options. Possibly this helper should be in `PactUtil` instead? I'm torn - it's specific to `can-i-deploy`, but it's not really the responsibility of the `CanDeploy` object.
* All the functions / classes here are named `CanDeploy`. I'm not sure if I should have used `CanIDeploy` instead?
* The first commit on this branch also bumped the …
=> Add can-i-deploy to API and CLI tool

bin/pact-cli.ts, src/can-deploy.ts
It was raised in Slack that this flag was missing - adding in now.
=> feat(can-deploy): add broker token to can-deploy task

README.md, bin/pact-broker.ts, bin/pact-message.ts, bin/pact-mock-service.ts, bin/pact-provider-verifier.ts, bin/pact-stub-service.ts, package.json
Expose the CLI as bin stubs for when the JS interface does not yet have new features, or when using JS APIs is not desirable.
=> feat(binstubs): expose pact standalone binaries as alternative CLI

package.json
I believe this fixes the broken builds that we're experiencing.
=> chore: move @types/request to a dependency rather than a devDependency

standalone/install.ts
=> fix: prevent archive extracting as the wrong user when installing as root

README.md, src/verifier.spec.ts, src/verifier.ts
=> fix(verifier): Allow to use progress formatter during verification

package-lock.json, package.json, standalone/install.spec.ts, standalone/install.ts
Uses `libnpmconfig` to cascade through the various npm config layers and set the property on the download object.
Didn't like exporting the function in order to test it, but I needed a few tests around it at the time. Perhaps they can go now?
=> fix: set strictSSL on custom downloads from NPM config. Fixes #211

README.md, src/spawn/arguments.spec.ts, src/spawn/arguments.ts, src/verifier.ts
Implements consumer version selectors (see https://github.com/pact-foundation/pact_broker/issues/307) and pending pacts (see ).
The biggest complication here is that the selectors are specified as JSON strings on the CLI - not something we're well prepared for.
In terms of design options I had a few, most notably:
1. Modify `verifier.ts` to do the JSON marshaling, but that then meant I needed to do nasty things to hide the true option that is passed to the `Arguments` class.
2. Enhance the `SpawnArguments` type to signal that certain properties were basic "string" values vs "JSON" values - but decided against that large refactor.
3. Detect an argument value - if it is an object, marshal to JSON, otherwise fall back to existing behaviour. This is the path I chose, because it was so simple …
=> feat: add consumer version selectors and pending pacts to verification

standalone/install.ts
For https://github.com/pact-foundation/pact-ruby-standalone/issues/49
=> fix: update standalone to 1.82.2

standalone/install.ts
fix for issue discovered whilst trying to use pactjs
https://github.com/pact-foundation/pact-js/issues/427
CA config does not work when a cafile is specified in .npmrc
=> fix: correcting the cafile setup for postinstall download

README.md, src/verifier.spec.ts, src/verifier.ts
* Adds `consumerVersionTags` and `providerVersionTags` as options that _only_ accept arrays. I think accepting a string or array is unnecessary.
* Logs deprecation warning if `consumerVersionTag` and `providerVersionTag` is used
* Supports both options until a major version bump.
=> feat: deprecate consumerVersionTag and providerVersionTag. Fixes #218

src/server.ts
In porting over amended changes from https://github.com/pact-foundation/pact-js/pull/489, my tests were routinely failing because the suite couldn't start the server with `logLevel` provided.
Then I discovered I had the same behavior in `master` when running tests locally.
Then I discovered [the latest CI build for `master` was failing for the same reason](https://travis-ci.org/github/pact-foundation/pact-node/builds/716505875).
Removing this line fixes the build locally for me. Marking this as a draft PR to see what CI does when it's submitted, or if anyone else has ideas about why this is failing. 🤷‍♀️ 
cc @TimothyJones
=> fix(server): remove force-clone of options

standalone/install.ts
When behind a proxy that implements SSL interception the CA file was not being set correctly.
I couldn't think of a way to add tests for this but if a way can be suggested I'm happy to implement them. I have however tested this locally behind an intercepting proxy.
This could possibly fix https://github.com/pact-foundation/pact-js/issues/485
=> fix: Correct the config for using custom ca file

README.md, src/spawn/arguments.spec.ts, src/verifier.ts
Fix incompatible `ConsumerVersionSelector` interface attributes based on [new pact_broker docs](https://docs.pact.io/pact_broker/advanced_topics/consumer_version_selectors/)
Fix: https://github.com/pact-foundation/pact-js/issues/649 and https://github.com/pact-foundation/pact-js-core/issues/285
=> fix: ConsumerVersionSelector interface (BREAKING CHANGE)

src/ffi/declarations.ts
Adding all of the FFI methods I've used in Pact Go, as well as some of the newer logging methods exposed.
I'm not sure about the Enums, but we're going to need them when we call the FFI functions in place of all of the `'int'` declarations. We can move them later, but I popped them in there now - thoughts?
Next step will be to expose a useful interface.
=> feat: add latest ffi methods to declarations

README.md, src/publisher.ts, test/publisher.integration.spec.ts
Add `buildUrl` parameter for the pact publication function. Follow-up for https://github.com/pact-foundation/pact-js-core/issues/352
=> feat: add build url on pact publish

src/spawn/arguments.spec.ts, src/spawn/arguments.ts, src/spawn/spawn.ts, src/verifier.ts
This should fix https://github.com/pact-foundation/pact-js/issues/782
=> fix: Serialize {enablePending: false} to --no-enable-pending

src/spawn/spawn.ts
This PR adds two environment variables, PACT_EXECUTING_LANGUAGE and PACT_EXECUTING_LANGUAGE_VERSION. These variables will be used to track metrics such as when consumer and provider tests are ran so that we(Pact OSS maintainers) can gain insight into what languages and versions are used for Pact. PRs for some of the metrics [here ](https://github.com/pact-foundation/pact-mock_service/pull/133) and [here](https://github.com/pact-foundation/pact-ruby/pull/256)
=> feat: collect usage telemetry data

src/verifier/validateOptions.spec.ts, src/verifier/validateOptions.ts
This PR fixes the changes made to validation in 13.7.3 which did not support the types specified for customProviderHeaders.  
Fixes (pact-foundation/pact-js-core#392)
=> fix: corrects customProviderHeaders validation

.eslintrc, src/verifier/argumentMapper/arguments.ts, src/verifier/argumentMapper/index.ts, src/verifier/argumentMapper/types.ts, src/verifier/validateOptions.ts
As discussed on slack, I've tidied up some types with the view to avoid bugs like the one raised in #general.
I've also uncovered some other things that are probably bugs - here's a list of what I did and did not fix:
* Removed a `l = l.toLowerCase() as LogLevel;` that had no effect (**this was probably a bug**, but now the code doesn't look like it is lowercasing the log level when it isn't. **I did not fix the bug**)
* Prevented use of `any` with an eslint rule and replaced the uses everywhere
* This is because `any` just turns off type safety. You should not need to do this
* Replaced the AssertFunction type pattern with one that doesn't need to look inside the checkTypes library (this wasn't compiling when I removed the `any`, so it wasn't the right type anyway). 
* I'm not sure what …
=> Avoid (some) type related bugs

README.md, src/publisher.ts
Addresses https://github.com/pact-foundation/pact-js/issues/749
Haven't added any tests in, but have tested with a local broker instance (spun up from the pact-workshop-js) repo
if `autoDetectVersionProperties` is true, but branch is set, it will use the provided `branch` value.
if `autoDetectVersionProperties` is true, but branch is not set, it will pick up the branch from my local machine
if `branch` is set, and is an empty string or undefined, no branch is set when uploading
if `branch` is set, is a valid string and `autoDetectVersionProperties` is not set to true, the user provided value is set
```
var pact = require('./src/pact');
var path = require('path');
const { Pact } = require('./src/pact');
var PactInstance = new Pact();
PactInstance.publishPacts({
pactBroker: …
```
=> feat: support branch/autoDetectVersionProperties when publishing pacts

standalone/install.ts
I'm not sure if pact-node is still being released, but this addresses [the regression](https://pact-foundation.slack.com/archives/C9VPNUJR2/p1669678385756549?thread_ts=1669658751.887949&cid=C9VPNUJR2) introduced in 10.17.3 - by updating the version to the main release instead of release candidate releases (which have longer version numbers, and are more likely to hit the long path issue)
=> fix: Update pact-ruby-standalone to 1.91.0, shortening the path for windows users

.github/workflows/build-and-test.yml, src/verifier/validateOptions.spec.ts, src/verifier/validateOptions.ts
This PR fixes an issue raised by [Gustavo Souza on slack here](https://pact-foundation.slack.com/archives/C9VBGLUM9/p1678279738564239), where an unknown key with an array value would cause the Verifier validation to fail with `cannot read property forEach of undefined`.
It also adds a test for this case.
The test also passes.
=> fix: Fix an issue where invalid VerifierOptions keys with Array values would cause a TypeError

src/logger/pino.ts
See: https://github.com/pinojs/pino-pretty#usage-with-jest
NB: This introduces a performance regression, but probably acceptable given this is a dev-only tool.
This seem to fix the issue showcased in https://github.com/Maxim-Filimonov/pact-js-jest-memory-leak-example. However, I'm slightly confused by `pino-pretty` - my logs don't even look pretty at all!
=> fix: Use synchronous logging to allow usage with Jest

package-lock.json, package.json, src/service.ts, src/types.ts
https://github.com/pact-foundation/jest-pact/pull/221 failed the build because of the way that Pact-JS-Core imports the needle type for re-export.
When I looked in to this, I saw that the needle type wasn't usable outside Pact-JS-Core (you wouldn't need it, and it can't be passed in). I don't think it was meant to be exported.
This PR fixes that by removing the custom `HTTPConfig` type entirely, since it wasn't really necessary (I'm not actually sure why it was there - perhaps I am missing something). 
It also moves the `@types/needle` dependency back to devDependencies.
=> fix: Remove unusable external export of HTTPConfig which removes the need to have needle types as a dependency

.cirrus.yml, .github/workflows/build-and-test.yml, DEVELOPER.md, script/ci/build-and-test.sh, script/lib/download-ffi.sh, test/consumer.integration.spec.ts, test/message.integration.spec.ts
- Consolidates CI test task to use single format for all three OS's
- Updates CI test task to use latest action tags (v3 checkout, v3 node)
- Remove steps no longer needed (updating node-gyp)
- Ensure FFI folder is deleted when running `download-libs.sh` otherwise it asks the user to confirm everytime. 🤯 
- Add a developer note to download the libs, before running `npm ci` when running locally
- Add macOS arm64/m1 runner test via Cirrus-CI
- Requires rosetta due to using v1.x of pact-ruby-standalone
- Add amd64/x86_64 linux test via Cirrus-CI in preparation for ARM64 linux testing in further PR to be raised
- Test ARM64 Linux, fails as expected as per issue #416
Cross CI provider and cross arch has shown a few inconsistencies in content-type matching, which is clearly demonstrable here. …
=> CI: Test across Node 16/18/20 + arm64 MacOS test

package-lock.json, package.json, script/lib/download-standalone.sh, src/pact-standalone.spec.ts, standalone/install.ts
Fix security vulnerabilities
Before:
```
semver  <7.5.2
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
No fix available
node_modules/conventional-changelog-writer/node_modules/semver
node_modules/cross-env/node_modules/semver
node_modules/eslint-config-airbnb-base/node_modules/semver
node_modules/git-semver-tags/node_modules/semver
node_modules/meow/node_modules/semver
node_modules/nodemon/node_modules/semver
node_modules/read-pkg/node_modules/semver
node_modules/semver
node_modules/simple-update-notifier/node_modules/semver
conventional-changelog-writer  *
Depends on vulnerable versions of meow
Depends on vulnerable versions of semver
node_modules/conventional-changelog-writer
conventional-changelog-core  * …
```
=> chore: upgrade for security vulnerabilities

.cirrus.yml, CHANGELOG.md, package-lock.json, package.json, script/lib/download-standalone.sh, src/pact-standalone.spec.ts, standalone/install.ts
PR's to Travelling ruby to update the supported archs
- https://github.com/phusion/traveling-ruby/pull/132
- https://github.com/phusion/traveling-ruby/pull/133
Which means we can now support
| OS     | Ruby      | Architecture | Supported |
| -------| ------- | ------------ | --------- |
| OSX    | 3.2.2     | x86_64       | ✅         |
| OSX    | 3.3.2     | aarch64 (arm)| ✅         |
| Linux  | 3.2.2   | x86_64       | ✅         |
| Linux  | 3.2.2   | aarch64 (arm)| ✅          |
| Windows| 3.2.2 | x86_64       | ✅        |
| Windows| 3.2.2 | x86       | ✅        |
| Windows| 3.2.2 | aarch64 (via x86 emulation) |  ✅        |
- https://github.com/pact-foundation/pact-ruby-standalone/pull/100
- https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v2.0.0
These have been …
=> Feat: ARM64 Linux/MacOS Pact Ruby Standalone

package.json
as per https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines the current config uses an incorrect key, so isn't picked up by tools like badgen and I assume others https://badgen.net/#npm/node/@pact-foundation/pact-core
=> fix: set engines in package.json not engine

.github/workflows/update-ffi.yml, script/create-pr-to-update-pact-ffi.sh, script/dispatch-ffi-released.sh
Aim:- Provide a CI workflow, that can be triggered on release of the Pact FFI library.
Relates to https://github.com/pact-foundation/pact-reference/issues/375 , specifically `Trigger dependant client libraries workflows to raise PR's`
This change borrows from the existing update workflow on release of the pact-ruby-standalone.
- release trigger 
- https://github.com/pact-foundation/pact-ruby-standalone/blob/3cecd6dce82922697f1ba2a3ccdabdaebdb54be9/.github/workflows/release.yml#L46-L63
1. Release point in Pact-reference project 
1.  https://github.com/pact-foundation/pact-reference/blob/fc33ad23e78698ecf1fb55eedb7dc228f96def17/.github/workflows/release.yml#L74-L81
1. Example Release
1. https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.14 
Our ci workflow for …
=> ci: update pact ffi on release workflow

native/consumer.cc, src/consumer/index.ts, src/ffi/types.ts
Migrates from `pactffi_response_status` to `pactffi_response_status_v2` to allow status code matching. Public interface is preserved to prevent breaking changes to intermediate Pact JS versions.
=> feat: support status code matcher via pactffi_response_status_v2

native/consumer.cc
Supports metadata with matching rules
- Fixes https://github.com/pact-foundation/pact-js/issues/1133
- Fixes https://github.com/pact-foundation/pact-js/issues/745
=> feat: add pactffi_message_with_metadata_v2

package.json
Add an "install" script to "override" npm behavior of adding a "node-gyp rebuild" install script on the fly when publishing.
=> fix: 🐛 avoid node-gyp rebuild install script

script/ci/prebuild.sh
Prebuildify is for some reason looking for node 22 headers, this change:
* sets node target based on current node version
* update to prebuildify 6.0.1 to fix windows EINVAL issue
=> chore: fix issue with prebuildify

bin/pact-broker.ts, bin/pact-message.ts, bin/pact-mock-service.ts, bin/pact-provider-verifier.ts, bin/pact-stub-service.ts, bin/pact.ts, bin/pactflow.ts
=> fix: node doesn't run .bat files on windows

src/ffi/index.ts
fixes https://github.com/pact-foundation/pact-js/issues/1216
Large number of pact verifications fail when run in parallel
=> fix: set process.stdout._handle.setBlocking(true) on ffi init

bin/pact-broker.ts, bin/pact-message.ts, bin/pact-mock-service.ts, bin/pact-provider-verifier.ts, bin/pact-stub-service.ts, bin/pact.ts, bin/pactflow.ts, src/pact-standalone.ts
- Initial issue 
- https://github.com/pact-foundation/pact-js-core/issues/503
- Fix
- https://github.com/pact-foundation/pact-js-core/pull/504
- Regressions
- fixes https://github.com/pact-foundation/pact-js-core/issues/506
- Cause(s)
- Change not scoped for only `win32` platform (windows only)
- use of `shell` does not behave the same with regards to escaping of provided user arguments
- Reproducers
- [Failing CI](https://github.com/YOU54F/pact-js/actions/runs/9271916204)
- [Passing CI](https://github.com/YOU54F/pact-js/actions/runs/9275156872)
⛔
`npx --package=@pact-foundation/pact-core@14.3.5 -c 'pact-broker publish "my pact.json" --consumer-app-version 1'`
✅
`npx --package=@pact-foundation/pact-core@14.3.4 -c 'pact-broker publish "my pact.json" --consumer-app-version 1'`
✅
`npx …
=> fix: shell escaping

bin/pact-broker.ts, bin/pact-message.ts, bin/pact-mock-service.ts, bin/pact-provider-verifier.ts, bin/pact-stub-service.ts, bin/pact.ts, bin/pactflow.ts, script/lib/download-file.sh, src/pact-standalone.ts, src/service.ts
Inform users of upcoming breaking change in #513 
Users may be setup to output in json format. This warning will appear conditionally I believe, so may mess up workflows if one if using the json output from stdout and now has a warning in it.
An option to silence the warnings is provided if `PACT_SILENCE_DEPRECATION_WARNINGS` is set to `true`
All CLI/API functionality provided by the Pact CLI tools (ruby based) will be moved in pact-js-core 15.x to pact-js-cli.
* Repo
* https://github.com/pact-foundation/pact-js-cli/
* NPM Package
* https://www.npmjs.com/package/@pact-foundation/pact-cli
* imports
* `@pact-foundation/pact-core` imports will now become `@pact-foundation/pact-cli` for programatic usage of the CLI tools
* npx usage
* `npx --package=@pact-foundation/pact-cli@15.0.1 -c …
=> fix: add deprecation warnings for pact cli tools in pact-js-core

.github/workflows/build-and-test.yml
Node 22.5.0 failing to successfully complete install
See https://github.com/nodejs/node/issues/53902
=> fix(deps): pin to node 22.4.1

.github/workflows/build-and-test.yml, src/ffi/index.ts, test/matt.consumer.integration.spec.ts, test/matt.provider.integration.spec.ts
Update to [libpact_ffi 0.4.22](https://github.com/pact-foundation/pact-reference/releases/tag/libpact_ffi-v0.4.22)
Includes [windows plugin shutdown fix](https://github.com/pact-foundation/pact-plugins/pull/67)
Introduces failures in windows matt plugin tests with tcp connections (solved by calling socket.end/destroy)
=> Chore/upgrade to pact ffi 0.4.22

.github/workflows/build-and-test.yml
Reverts pact-foundation/pact-js-core#518
22.5.1 now released (which should contain fix)
=> Revert "fix(deps): pin to node 22.4.1"

native/addon.cc, native/ffi.cc, package.json, src/consumer/index.ts, src/ffi/index.ts, src/verifier/nativeVerifier.ts, src/verifier/types.ts, src/verifier/validateOptions.ts, test/consumer.integration.spec.ts, test/matt.consumer.integration.spec.ts
Will go someway to address https://github.com/pact-foundation/pact-js/issues/954
(will need adding into pact-js)
Passed in via an optional param, to `getFfiLib` which is called by a couple of functions, as an optional param. Wonder if it would be better to have these in an opts object that can take named params.
note, the option used to be called `log` in pact-js v2 and is moved to deprecated now. should we retain `log` or use a more descriptive `logFile`
https://github.com/pact-foundaton/pact-js/tree/9.x.x#constructor
need to add some appropriate tests and refactor based on review comments :)
=> feat: add pactffi_log_to_file for consumer/verifier

src/ffi/index.ts, src/ffi/types.ts
the existing enum FfiLogLevelFilter was not used, and its values
LOG_LEVEL_* as not the same as LogLevel types
LogLevel = debug | error | info | trace | warn;
This fixes it for the verifier exposed in pact-js, automatically consuming this fix release.
pact-js consumer interfaces, still require updating to pass in the logFile argument.
=> fix: logFile default to info if undefined, warn if error setting

.github/workflows/build-and-test.yml
We don't need to run CI on every push to any branch _and_ PRs targetting master. This change ensures that the following are targetted:
- New commits to `master`
- PRs targetting `master`
Specifically, commits to new branches are _not_ tested unless they are part of a PR.
=> chore(ci): deduplicate CI runs

.github/workflows/build-and-test.yml
arm64 runners now available, so lets use them to speed up our CI runs
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
=> ci: use arm runners for arm64 workflows
