pact-foundation/pact-js-core

- README.md
- package.json
- src/logger.js
- src/pact.js
- src/pact.spec.js
- src/publisher.js
- src/server.js
- src/verifier.spec.js
- test/integration/provider.js
- test/mocha.opts
- test/verifier.integration.spec.js
A couple of improvements. I've used `pact-node` on another project and prefer it to be less verbose. So here's a PR along with a couple of other enhancements.
> Optional logging

- src/publisher.js
- test/integration/brokerMock.js
> Allow 20x responses from pact broker on publish (issue #16)

- .editorconfig
Basically this: http://editorconfig.org/
Install the (plugin to your favourite editor)[http://editorconfig.org/#download] and watch it magically transform your code. It works pretty well.
> add an '.editorconfig' file for consistent code style across editors

- test/integration/me-they-post-regex-success.json
- test/integration/me-they-post-success.json
- test/integration/provider.js
- test/verifier.integration.spec.js
Hey @mefellows @mboudreau ,
I looked to the tests to find a good way of testing POST:s, regex, etc, but couldn't find any so I added some.
Would it be possible to add something similar? :)
// callebstrom
> Added POST test. Added POST regex test

- package.json
- src/server.ts
- src/verifier.ts
See https://github.com/pact-foundation/pact-node/pull/45 for the non-TS implementation of the same feature.
> feat(standalone): add pact standalone to TS implementation

- src/server.ts
> fix(server): fix NPE in create server setup

- README.md
- bin/pact-cli.ts
- src/server.spec.ts
- src/server.ts
Exposes this field to pact node. Fixes #50
> feat(pactFileWriteMode): add pactFileWriteMode to server. Fixes #50

- bin/pact-cli.spec.ts
- bin/pact-cli.ts
publish command was missing from CLI, adding it.  Fixing a few things with the CLI covention, non breaking.
> feat(cli): adding publish to CLI commands

- standalone/install.ts
Addresses https://github.com/pact-foundation/pact-node/issues/149
> Specify User-Agent when downloading binaries

- src/can-deploy.spec.ts
- src/can-deploy.ts
- test/integration/broker-mock.ts
Fix for issue #153 , not using the status reason but json value or text from ruby binary to determine success/failure
> Fix can i deploy incorrect failures

- README.md
- src/verifier.spec.ts
- src/verifier.ts
> Vgrigoruk fix/consumer version tag array

- bin/pact-broker.ts
- bin/pact-message.ts
- bin/pact-mock-service.ts
- bin/pact-provider-verifier.ts
- bin/pact-stub-service.ts
Fixes https://github.com/pact-foundation/pact-node/issues/163
> Propagate exit code in node CLI wrapper

- package-lock.json
- package.json
- This PR fixes `package-lock.json`, which is  is currently out of sync with `package.json`
- Removes duplicated `snyk` entries in `package.json`
- Moves `snyk` to `devDependencies`, as it is not needed for runtime.
> fix(package.json): Move snyk to devDependencies

- standalone/install.ts
For https://github.com/pact-foundation/pact-net/issues/237
> fix: update standalone to 1.82.3

- standalone/install.ts
Might fix https://github.com/pact-foundation/pact-js/issues/446
> fix: update standalone to 1.85.0

- standalone/install.ts
Please expose the --log-dir and --log-level options to the native API.
> feat: update standalone to 1.86.0

- standalone/install.ts
Reverts pact-foundation/pact-js-core#322
> Revert "fix: update standalone to 1.88.68"

- src/verifier.spec.ts
- src/verifier.ts
- standalone/install.ts
Fixes https://github.com/pact-foundation/pact-js/issues/750 (for the `pact-node` package)
> feat: support specifying provider branch in verifications

- .github/workflows/build-and-test.yml
> fix: native builds started failing on windows

- bin/pactflow.ts
- package-lock.json
- package.json
> Expose pactflow command

- bin/pactflow.ts
- src/pact-standalone.spec.ts
- src/pact-standalone.ts
pactflow command incorrectly mapped to wrong binary - added the complete change in now
> fix: map pactflow command to correct binary / add tests

- src/verifier/argumentMapper/arguments.ts
- src/verifier/argumentMapper/index.ts
> fix: error if file source is invalid

- .gitignore
- binding.gyp
- script/lib/download-ffi.sh
- src/ffi/internals/index.spec.ts
- src/ffi/internals/index.ts
This seems to get all things going that are not using the Ruby standalone binaries.
> feat: Add Linux/arm64 support

- native/addon.cc
- native/provider.cc
- native/provider.h
- src/ffi/types.ts
- src/verifier/argumentMapper/arguments.ts
- src/verifier/types.ts
- src/verifier/validateOptions.ts
> Adamwitko add no fail if no pacts

- package-lock.json
- package.json
- src/logger/pino.ts
> fix: upgrade to latest pino

- .cirrus.yml
- package.json
- src/ffi/index.ts
This might actually be best being a `fix!` and a new major version. I'm actually unclear on the appropriate semver bump required for this.
> fix: drop support for node 15 and earlier

- src/ffi/index.ts
- test/consumer.integration.spec.ts
_Please read and then remove this section_
Thank you for making a pull request!
Pact-js-core is built and maintained by developers like you, and we appreciate contributions very much. You are awesome!
Our changelog is automatically built from our commit history, using conventional changelog. This means we'd like to take care that:
- commit messages with the prefix `fix:` or `fix(foo):` are suitable to be added to the changelog under "Fixes and improvements"
- commit messages with the prefix `feat:` or `feat(foo):` are suitable to be added to the changelog under "New features"
If you've made many commits that don't adhere to this style, we recommend squashing 
your commits to a new branch before making a PR. Alternatively, we can do a squash
merge, but you'll lose attribution for your …
> Fix/update core 0.4.7

- RELEASING.md
Just a quick documentation fix while i was browsing the code.
> Fixes a line break issue

- .github/workflows/build-and-test.yml
Ref: actions/runner-images#10721
> chore(ci): upgrade macos-12 to macos-13

- native/addon.cc
- native/consumer.cc
- native/consumer.h
- src/consumer/index.ts
- src/consumer/types.ts
- src/ffi/types.ts
- test/message.integration.spec.ts
Supports handling request/response bodies in Synchronous messages.
> feat: support fetching bodies for messages
